name: dotnet package

on: [push]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration ${{ matrix.configuration }} --no-restore
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: SightKeeper-${{ matrix.configuration }}
          path: SightKeeper.Avalonia/bin/${{ matrix.configuration }}/net7.0-windows
